### ISSUE TITLE
Execution cannot be stopped or interrupted under Python 3.7 on Windows

### ISSUE THREAD

**Issue by CAM-Gerlach** [ipython/ipykernel#374] opened 2018-11-30 00:57 UTC
@minrk Per @ccordoba12 's request, I'm reporting this here and pinging you since the problem appears to be with ``ipykernel``. We've gotten many reports of this from other Spyder users as well, who are very frustrated with this behavior to the point where they are considering switching IDEs. This was originally reported on our tracker as  spyder-ide/spyder#8013 , as well as several other places.

## Problem Description

Under Python 3.7 (but *not* Python 3.6) on Windows, execution cannot apparently cannot be stopped or interrupted while it is running, either by the stop button in Spyder, the "Interrupt kernel" option under the Kernel menu in QtConsole, or pressing ``Ctrl-C`` in either. I tested on my Linux VM (Fedora 28) on the same machine, and everything worked under identical versions of ``ipython``, ``ipykernel``, ``python``, ``jupyter_core`` and ``jupyter_client`` on both Python 3.6 and Python 3.7. On Windows, it often takes a Ctrl-C to register, but it always does eventually on Python 3.6 and prints the ``KeyboardInturrpt`` traceback while the prompt just returns normally on Python 3.7; on Linux, of course, it returns instantly with the ``KeyboardInturrpt`` on both Pythons.

## Steps to Reproduce

1. Open a QtConsole instance under Python 3.7 on Windows
2. Run ``import time; time.sleep(10)``
3. Try to interrupt execution by Ctrl-C or the menu option

## Tested Versions

The below versions all experienced the problem behavior on Python 3.7, and not on Python 3.6 or on Linux:

OS: Windows 8.1 x64: yes, Fedora 28 x64: no
Python: 3.6.5, 3.6.6, 3.6.7: No, 3.7.0, 3.7.1: Yes
IPykernel: 4.8.2, 4.10.0, 5.0.1, 5.1.0 (latest)
IPython: 6.5.0, 7.0.1, 7.1.0, 7.1.1 (latest)
QtConsole: 4.3.1, 4.4.1, 4.4.2 (latest)
Jupyter_Client: 5.2.3 (latest)
Jupyter_Core: 4.4.0 (latest)
PyZMQ: 17.1.2 (latest)

## Conda list output

<details>

```
# packages in environment at C:\Anaconda3\envs\spyder-test:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.11                   py37_0
asn1crypto                0.24.0                   py37_0
astroid                   2.0.4                    py37_0
atomicwrites              1.2.1                    py37_0
attrs                     18.2.0           py37h28b3542_0
babel                     2.6.0                    py37_0
backcall                  0.1.0                    py37_0
bleach                    2.1.4                    py37_0
ca-certificates           2018.03.07                    0
certifi                   2018.10.15               py37_0
cffi                      1.11.5           py37h74b6da3_1
chardet                   3.0.4                    py37_1
cloudpickle               0.5.6                    py37_0
colorama                  0.3.9                    py37_0
coverage                  4.5.1            py37hfa6e2cd_0
cryptography              2.3.1            py37h74b6da3_0
cycler                    0.10.0                   py37_0
cython                    0.28.5           py37h6538335_0
decorator                 4.3.0                    py37_0
docutils                  0.14                     py37_0
entrypoints               0.2.3                    py37_2
fastcache                 1.0.2            py37hfa6e2cd_2
flaky                     3.4.0                    py37_0
freetype                  2.9.1                ha9979f8_1
html5lib                  1.0.1                    py37_0
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                 ha66f8fd_1
idna                      2.7                      py37_0
imagesize                 1.1.0                    py37_0
intel-openmp              2018.0.3                      0
ipykernel                 5.1.0            py37h39e3cac_0
ipython                   7.1.1            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
isort                     4.3.4                    py37_0
jedi                      0.12.1                   py37_0
jinja2                    2.10                     py37_0
jpeg                      9b                   hb83a4c4_2
jsonschema                2.6.0                    py37_0
jupyter_client            5.2.3                    py37_0
jupyter_core              4.4.0                    py37_0
keyring                   13.2.1                   py37_0
kiwisolver                1.0.1            py37h6538335_0
lazy-object-proxy         1.3.1            py37hfa6e2cd_2
libpng                    1.6.34               h79bbb47_0
libsodium                 1.0.16               h9d3ae62_0
libtiff                   4.0.9                hb8ad9f9_1
markupsafe                1.0              py37hfa6e2cd_1
mccabe                    0.6.1                    py37_1
mistune                   0.8.3            py37hfa6e2cd_1
mock                      2.0.0                    py37_0
more-itertools            4.3.0                    py37_0
mpmath                    1.0.0                    py37_2
nbconvert                 5.3.1                    py37_0
nbformat                  4.4.0                    py37_0
numpydoc                  0.8.0                    py37_0
olefile                   0.46                     py37_0
openssl                   1.0.2p               hfa6e2cd_0
packaging                 18.0                     py37_0
pandoc                    2.2.1                h1a437c5_0
pandocfilters             1.4.2                    py37_1
parso                     0.3.1                    py37_0
pbr                       4.2.0                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    5.2.0            py37h08bbbbd_0
pip                       10.0.1                   py37_0
pluggy                    0.7.1            py37h28b3542_0
prompt_toolkit            2.0.5                    py37_0
psutil                    5.4.7            py37hfa6e2cd_0
py                        1.6.0                    py37_0
pycodestyle               2.4.0                    py37_0
pycparser                 2.19                     py37_0
pyflakes                  2.0.0                    py37_0
pygments                  2.2.0                    py37_0
pylint                    2.1.1                    py37_0
pyopenssl                 18.0.0                   py37_0
pyparsing                 2.2.1                    py37_0
pyqt                      5.9.2            py37h6538335_2
pysocks                   1.6.8                    py37_0
pytest                    3.9.1                    py37_0
pytest-cov                2.6.0                    py37_0
pytest-mock               1.10.0                   py37_0
pytest-timeout            1.3.2                    py37_0
python                    3.7.1                h33f27b4_4
python-dateutil           2.7.3                    py37_0
pytz                      2018.5                   py37_0
pywin32                   223              py37hfa6e2cd_1
pyzmq                     17.1.2           py37hfa6e2cd_0
qt                        5.9.6            vc14h1e9a669_2
qtawesome                 0.5.0                    py37_0
qtconsole                 4.4.2                    py37_0
qtpy                      1.5.1                    py37_0
requests                  2.19.1                   py37_0
rope                      0.11.0                   py37_0
setuptools                40.4.3                   py37_0
simplegeneric             0.8.1                    py37_2
sip                       4.19.8           py37h6538335_0
six                       1.11.0                   py37_1
snowballstemmer           1.2.1                    py37_0
sphinx                    1.8.1                    py37_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-websupport  1.1.0                    py37_1
spyder                    3.3.2                    py37_0
spyder-kernels            0.2.6                    py37_0
sqlite                    3.24.0               h7602738_0
sympy                     1.3                      py37_0
testpath                  0.4.1                    py37_0
tk                        8.6.7                hcb92d03_3
tornado                   5.1.1            py37hfa6e2cd_0
traitlets                 4.3.2                    py37_0
urllib3                   1.23                     py37_0
vc                        14.1                 h0510ff6_3
vs2015_runtime            15.5.2                        3
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
wheel                     0.32.0                   py37_0
win_inet_pton             1.0.1                    py37_1
wincertstore              0.2                      py37_0
wrapt                     1.10.11          py37hfa6e2cd_2
zeromq                    4.2.5                he025d50_1
zlib                      1.2.11               h8395fce_2
```

</details>

**Comment by minrk** [comment] 2018-11-30 08:34
Thanks for reporting this. I'll see if I can figure it out. Windows interrupts work by sending a Windows event, so perhaps something in Python 3.7 changed how that works (we're just using ctypes to call kernel32 methods, so I'm not sure how).

The sending code is [in jupyter_client](https://github.com/jupyter/jupyter_client/blob/5.2.3/jupyter_client/win_interrupt.py) and the handler is [in ipykernel](https://github.com/ipython/ipykernel/blob/5.1.0/ipykernel/parentpoller.py#L46).

**Comment by CAM-Gerlach** [comment] 2018-11-30 08:42
Thanks @minrk ! Let me know if you need me to help test something.

**Comment by minrk** [comment] 2018-11-30 09:12
I created a py37 env and a py36 env and the *client* appears to be the version that matters most. A Python 3.7 qtconsole cannot interrupt a Python 3.6 kernel, but a Python 3.6 qtconsole can interrupt Python 3.7.

**Comment by minrk** [comment] 2018-11-30 11:33
I've been trying to isolate the cause, calling the SetEvent and WaitForMultipleObjects directly in [this test script](https://gist.github.com/minrk/1c04467b97a1d72f81a8b96dfd0fb297). And the script works on py36 but not py37.

What's absolutely bizarre is that it fails on both in the same way if I don't have `stdin=PIPE`. It makes no sense whatsoever that stdin of the subprocess would need to be a PIPE in order for the child to wait on events, but I'll dig in. I'm guessing that's our lead to the difference between 3.6 and 3.7.

**Comment by minrk** [comment] 2018-11-30 12:20
The stdin=PIPE was enough of a breadcrumb to lead me to the [change in `close_fds`](https://docs.python.org/3/library/subprocess.html?highlight=close_fds#subprocess.Popen) behavior in 3.7. `close_fds` defaults to True on non-Windows. Prior to 3.7, on Windows it defaults to `not any_fd_redirected`, but 3.7 it is consistent with non-Windows and just True, closing all non-std FDs by default. This behavior is closing the handles we are trying to pass to the subprocess, preventing the interrupt behavior.

I'm just going to confirm that this fixes the issue, then I'll open a PR.

**Comment by ccordoba12** [comment] 2018-11-30 14:02
Thanks a lot @minrk for the quick response!

**Comment by CAM-Gerlach** [comment] 2018-11-30 15:57
Thanks so much @minrk !

**Comment by ccordoba12** [comment] 2018-11-30 16:01
@CAM-Gerlach, can you confirm that Min's PR in jupyter_client effectively fixes the problem?

**Comment by CAM-Gerlach** [comment] 2018-12-01 00:12
@CAM-Gerlach After resolving some issues, I can indeed confirm it fixes the stated problem. Thanks @minrk  and @ccordoba12 !

**Closed** 2018-12-01 20:56 UTC

**Comment by SaumyaShikhar** [comment] 2018-12-31 05:05
Hi. I am facing the same issue. Can you let me know what change I need to make to get rid of it?

**Comment by CAM-Gerlach** [comment] 2018-12-31 23:36
@SaumyaShikhar Update ``jupyter_client`` to 5.2.4 (e.g. with ``conda update jupyter_client``) to get the fix.
