### ISSUE TITLE
conda install ipywidgets requires another jupyter notebook install?

### ISSUE THREAD

**Issue by michaelaye** [ipython/ipykernel#70] opened 2015-10-23 06:58 UTC
I'm trying to run `jupyter notebook` from a root conda environment, with the kernels installed in the correct `--data-dir`, with an absolute path pointing to the conda environment for that kernel:
```json
{
 "display_name": "Python 3",
 "argv": [
  "/Users/klay6683/miniconda3/envs/py34/bin/python",
  "-m",
  "ipykernel",
  "-f",
  "{connection_file}"
 ],
 "language": "python"
}
```
but without installing another jupyter notebook in the conda environments.
But some of my libraries use widgets, so they do import from `ipywidgets`, which I don't have installed. Independently (it seems), even before I try to import my modules that use ipywidgets, just to see what happens, in the notebook console I see this happening, (which is why I report here:)
```python
[I 00:40:58.805 NotebookApp] Kernel started: 65371f66-b64e-459b-a669-c8cda9f856fe
[IPKernelApp] ERROR | No such comm target registered: ipython.widget
```
But when I try to install only the `ipywidgets`, conda wants to install the whole she-bang it seems:
```bash
$ conda install ipywidgets
Fetching package metadata: ....
Solving package specifications: ..................................
Package plan for installation in environment /Users/klay6683/miniconda3/envs/py34:

The following NEW packages will be INSTALLED:

    certifi:    2015.9.6.2-py34_0
    ipywidgets: 4.1.0-py34_0
    jsonschema: 2.4.0-py34_0
    mistune:    0.7.1-py34_0
    nbconvert:  4.0.0-py34_0
    nbformat:   4.0.1-py34_0
    notebook:   4.0.6-py34_0
    ptyprocess: 0.5-py34_0
    pygments:   2.0.2-py34_0
    terminado:  0.5-py34_1
    tornado:    4.2.1-py34_0
```
after which above error message disappears.

My relevant conda packages installed before the above were:
```bash
$ conda list|grep -i jupy
jupyter_client            4.1.1                    py34_0
jupyter_core              4.0.6                    py34_0
(py34)
klay6683 at macd2860 in ~
$ conda list|grep -i ipy
ipykernel                 4.1.1                    py34_0
ipython                   4.0.0                    py34_1
ipython_genutils          0.1.0                    py34_0
```

My question is, is this unavoidable, a conda problem, or am I still doing something wrong?
On a side note, when I tried the full path method to install kernels like so:
```bash
/Users/klay6683/miniconda/envs/py34/bin/python -m IPython kernelspec install-self
```
this installed the kernel into `/usr/local/share/jupyter/kernels` instead of into `jupyter --data-dir` which is `/Users/klay6683/Library/Jupyter` on my system.

**Comment by michaelaye** [comment] 2015-10-26 22:35
I understand the above sidenote case is happening when the kernelspec is installed for the system instead for the user?

**Comment by damianavila** [comment] 2015-10-29 19:38
Try installing `ipywigets` without dependencies...

```
conda install ipywidgets --no-deps
```

to avoid installing the notebook all other pieces again where you only want the kernel to live...

**Comment by michaelaye** [comment] 2015-10-29 19:40
ah, thanks. somehow i didn't think that conda should be able to do that, but of course that makes sense.

**Comment by takluyver** [comment] 2016-01-18 17:22
The issue would be that conda's ipywidgets package depends on the notebook package - in fact, [so does](https://github.com/ipython/ipywidgets/blob/9593226614c2fe10d1f222b5af7b904bcf494dbd/setup.py#L231) the PyPI package. Normally, that makes sense, because there's not much point in having the widgets without the notebook, but if you have an environment for a separate kernel without the notebook server installed, it's fine to install ipywidgets without notebook.

For now the solution is `--no-deps`, which also works for pip, I think. Someone might want to file a bug on [ipywidgets](https://github.com/ipython/ipywidgets/issues) to consider dropping the dependency on notebook.

Closing here, since it's not a bug in ipykernel.

**Closed by takluyver** 2016-01-18 17:22 UTC
