### ISSUE TITLE
Qt slow in Spyder when using ipykernel 5.3.3 (5.3.2 OK)

### ISSUE THREAD

**Issue by 8bit-Dude** [ipython/ipykernel#528] opened 2020-07-21 01:32 UTC
I am using Spyder 4.1.4 on Miniconda3-py37-4.8.3.
I noticed that matplotlib was unsually slow in IPython when using the Qt backend.
Downgrading ipykernel with conda to version 5.3.0 can however fix the issue.

**Comment by blink1073** [comment] 2020-07-21 09:53
@ccordoba12 might this be related to https://github.com/ipython/ipykernel/pull/525?

**Comment by DiegoF90** [comment] 2020-07-21 11:11
I also have the same issue, matplotlib seems to be very slow with the new Spyder 4.1.4.
I am not sure if it is related to #525, but I had already done the change suggested by @ccordoba12 [here](https://github.com/ipython/ipykernel/commit/4a05435220c730605ab454001ac3ecc364299736#diff-773c85e45dc4aacc95746531e6f97afe) and faced this issue later.

**Comment by DiegoF90** [comment] 2020-07-21 15:35
I do not know if this is related or f any use but, I was trying to use Tkinter as the graphics backend to see if the speed improved, but after restarting Spyder to apply this changes I got:

```python-traceback

ERROR:tornado.application:Exception in callback functools.partial(<function Kernel.enter_eventloop.<locals>.advance_eventloop at 0x000001D8E9EA4AF0>)
Traceback (most recent call last):
  File "C:\Users\1520797\AppData\Local\conda\conda\envs\gmv\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\Users\1520797\AppData\Local\conda\conda\envs\gmv\lib\site-packages\ipykernel\kernelbase.py", line 314, in advance_eventloop
    eventloop(self)
  File "C:\Users\1520797\AppData\Local\conda\conda\envs\gmv\lib\site-packages\ipykernel\eventloops.py", line 238, in loop_tk
    app.tk.createfilehandler(stream.getsockopt(zmq.FD), READABLE, notifier)
AttributeError: '_tkinter.tkapp' object has no attribute 'createfilehandler'

```

Which is the file referenced from which the problem seems to come from in #525 ?

**Comment by DiegoF90** [comment] 2020-07-21 17:08
I realized that I was already using 5.3.0 but with the changes suggested in [here](https://github.com/ipython/ipykernel/commit/4a05435220c730605ab454001ac3ecc364299736#diff-773c85e45dc4aacc95746531e6f97afe) (which I am guessing was included in 5.3.3) and matplotlib was still very slow. I then rolled back the changes and matplotlib started working as normal again. Maybe the changes have to be further reviewed so that they fix [this](https://github.com/spyder-ide/spyder/issues/13275) but do not introduce this slow behaviour for matplotlib?

**Comment by ccordoba12** [comment] 2020-07-21 17:54
@DiegoF90, thanks for confirmation. Could you let us know in what way Matplotlib is slow? I did some simple testing for PR #525 and things were working fine for me.

**Comment by AndrewAmmerlaan** [comment] 2020-07-21 18:04
I have the same problem with 5.3.3, plot windows are slow, the save button is completely unresponsive. There are no issues when running the same script through any terminal directly with python. (See also the issue that @ccordoba12 mentioned above)

Downgrading to version 5.3.2 fixed these problems

**Comment by ccordoba12** [comment] 2020-07-21 18:05
@blink1073, one solution to this would be to exclude the control channel completely from the Qt event loop for now. That will solve the issue fixed in #525 and also this one.

However, I don't know what implications that could have for the JupyterLab debugger. Pinging @SylvainCorlay about that.

**Comment by DiegoF90** [comment] 2020-07-21 19:54
Hi @ccordoba12 thanks for looking into this. As @AndrewAmmerlaan mentions, the Figure window after plotting even simple graphs becomes very unresponsive. It takes longer than usual just to switch to this window. Other processes that are usually done in almost real time take second: e.g. if you activate the grid `ax.grid()`, the Figure window shows at the bottom left the x and y coordinates at the same time as you move around the mouse. Showing the coordinates after 5.3.3. takes around to second to update for each position.

**Comment by 8bit-Dude** [comment] 2020-07-22 00:16
I also confirmed that the issue does not occur in version 5.3.2.

**Comment by raphaelquast** [comment] 2020-07-22 09:02
... just to add myself to the list here...
i can also confirm that matplotlib is very very slow after updating from 5.3.2 to 5.3.3

**Comment by ccordoba12** [comment] 2020-07-22 17:29
Hey everyone, could you help us to test pull request #531 to see if it fixes this problem and also the warnings issue that pull request #525 tried to fix?

We'd really appreciate your help in order to no release another faulty version. Thanks!

**Comment by AndrewAmmerlaan** [comment] 2020-07-22 17:42
> Hey everyone, could you help us to test pull request #531 to see if it fixes this problem and also the warnings problem that pull request #525 tried to fix?
> 
> We'd really appreciate your help in order to not release another faulty version. Thanks!

This patch fixes the slowness for me :smile:, not sure if it fixes the original issue that https://github.com/ipython/ipykernel/pull/525 tried to fix, but I don't see "a flush of warnings" that that PR mentions so I guess it fixes that too.

Thanks :+1:

**Comment by DiegoF90** [comment] 2020-07-22 18:32
Hi @ccordoba12, I think that just did the trick! I can confirm it fixes both this and #525 on my side!
Cheers mate 👍!

**Closed** 2020-07-22 19:11 UTC

**Comment by ccordoba12** [comment] 2020-07-22 21:09
Thanks a lot @AndrewAmmerlaan and @DiegoF90 for your help!

**Comment by 8bit-Dude** [comment] 2020-07-23 01:44
Thanks for quickly addressing the issue!

**Comment by raphaelquast** [comment] 2020-07-23 06:22
@ccordoba12 thanks for this quick fix!!!  (even though it's already too late.... I can confirm that all works as expected now!)
