### ISSUE TITLE
`asyncio` and `concurrent.futures.ProcessPoolExecutor` prevent kernel restarts

### ISSUE THREAD

**Issue by jbweston** [ipython/ipykernel#274] opened 2017-10-27 13:00 UTC
The problem is illustrated in [this notebook](https://nbviewer.jupyter.org/url/joseph.weston.cloud/uploads/kernel-restart-problem.ipynb).

If I use the `asyncio` event loop integration introduced in #21 along with `concurrent.futures.ProcessPoolExecutor` then hitting the "restart" button from within the notebook interface is broken. The notebook server attempts 5 times to restart the kernel, then gives up and creates a "new" one. The previous kernel process is then orphaned, but still exists on the system (with the `init` process as the parent).

This is a problem because there is a sizeable delay between hitting "restart" and being able to use a new kernel. Also this produces many orphan processes that take resources and do not go away even once the notebook server is stopped.

**Comment by jbweston** [comment] 2017-10-27 13:01
The problem is not present if any `ProcessPoolExecutor`s are `shutdown` prior to hitting "restart".

**Comment by minrk** [comment] 2017-11-15 14:06
There's a good chance that https://github.com/jupyter/jupyter_client/pull/279 alleviates this, as it is not an uncommon situation to be in where restart doesn't fully clean up subprocesses and the result is a forked subprocess holding on to its parent's FD that the new kernel needs to restart, ultimately running into EADDRINUSE.

Does it require asyncio *and* ProcessPool, or just ProcessPool to run into this? It's possible that we can do more to clean up process trees, either here or in jupyter_client.

**Comment by jbweston** [comment] 2017-11-15 15:35
> Does it require asyncio and ProcessPool, or just ProcessPool to run into this? It's possible that we can do more to clean up process trees, either here or in jupyter_client.

It requires both, and it requires that the `asyncio` event loop integration be used with `%gui asyncio`.
Without this the kernel will happily restart.

**Comment by basnijholt** [comment] 2017-11-27 12:00
@minrk unfortunately https://github.com/jupyter/jupyter_client/pull/279 does not solve the issue (also I am using https://github.com/ipython/ipykernel/pull/281).

**Comment by minrk** [comment] 2017-11-27 21:40
I don't have a fix yet, but I've narrowed this down to a couple of things:

1. on clean exit, ProcessPools clean up their children
2. `%gui asyncio` (`%gui anything, actually) prevents clean shutdown, thus preventing `atexit` cleanup from firing
3. when clean shutdown fails, jupyter-client kills the kernel more forcefully
4. when killing the kernel, we do not kill the process *group*, even though we do have code to do this in `signal_kernel`, a different path is used for kill.

I think we should fix *both* gui-registration preventing clean exit (an ipykernel issue) and killing the process group (a jupyter-client issue), but either one ought to fix this.

FWIW, I was able to recover my kernel thanks to jupyter/jupyter_client#279. It does fail to restart initially, but after a few retries it gets new ports and is able to come back.

**Comment by basnijholt** [comment] 2017-12-10 00:57
Fixing it sounds like a lot of work. 

But the problem is quite a bit more annoying than you would think; after you restarted sufficiently many times, the whole machine becomes unusable until you either manually kill all processes or just restart my Docker container.

Would all of those things have to be solved to get it to behave?

**Comment by minrk** [comment] 2017-12-12 15:22
> Would all of those things have to be solved to get it to behave?

No, I think if *any* of those is fixed, it will behave in this case. But fixing them all would ensure similar issues don't crop up again.

The first fix should really be in ipykernel, figuring out why we don't exit cleanly for simple cases like this. With that fixed, jupyter-client solidly shutting down process groups is a bit less urgent. It shouldn't be a lot of work, but it's a relatively complex bit of logic. I'll try to find a window to look into it.

**Comment by minrk** [comment] 2017-12-12 15:29
The central issue is the exit is handled [here](https://github.com/ipython/ipykernel/blob/4.7.0/ipykernel/zmqshell.py#L473), where we directly stop the tornado eventloop. This isn't enough when another eventloop (asyncio in this case) is also running. Registering an additional hook to stop the integrated eventloop at exit should do it.

**Comment by minrk** [comment] 2017-12-15 13:29
This should be doubly fixed:

- IPython clean-exit when eventloops are active should be fixed by #290
- jupyter-client killing process groups when kernels *don't* exit cleanly should be fixed by jupyter/jupyter_client#314

**Closed** 2017-12-19 09:41 UTC
