### ISSUE TITLE
Error opening new comm

### ISSUE THREAD

**Issue by bollwyvl** [ipython/ipykernel#1059] opened 2022-12-16 21:07 UTC
With the `6.19.x` line, i'm seeing this in [this gist](https://gist.github.com/bollwyvl/543d7bc10705dd4006494f21aa48ca92).

![image](https://user-images.githubusercontent.com/45380/208188419-dc6aa6b4-acf9-4785-9edb-b0d4508d186b.png)

Rolling back to `6.17.1` does not show this behavior. 

The `target_name: "comm"` is suspect. Having a further look, but this seemed like a useful minimum reproducer to explore further.

**Comment by bollwyvl** [comment] 2022-12-16 21:29
Some more data:
- with `6.17.x`, creating the slider results in 3 `comm_open` messages
  - all have the `jupyter.widget` target
- with `6.19.x`, the same generates 6 `comm_open` messages
  - 3 with `comm` target
  - 3 with `jupyter.widget` target

**Comment by maartenbreddels** [comment] 2022-12-16 21:32
Ouch, hope I don’t have to eat my laptop. 
weird, because we had multiple confirmations 6.19.2 made widgets work.

**Comment by bollwyvl** [comment] 2022-12-16 21:37
yeah, dunno... but can confirm that pinning to `!=6.19.*` has unbroken some of my downstream CI jobs.

**Comment by maartenbreddels** [comment] 2022-12-16 21:40
Happy to take another look after the weekend, thanks for reporting!

**Comment by maartenbreddels** [comment] 2022-12-16 21:52
Sorry for this, this is caused a lot of pain already.

**Comment by maartenbreddels** [comment] 2022-12-19 13:48
@bollwyvl I think this is fixed in https://github.com/ipython/ipykernel/pull/1056#issuecomment-1357698259 but I am not sure, since I cannot reproduce this :(

Could you try running that branch? Or maybe you have ideas on how to reproduce this locally.

**Comment by bollwyvl** [comment] 2022-12-19 14:01
I've updated the gist with a `git+https` pointer to the head of that branch, and no longer see the problem. :tada:

**Closed** 2022-12-19 14:22 UTC

**Comment by bollwyvl** [comment] 2022-12-19 22:46
I'm seeing some more issues... will try to create another reproducer and open a new issue.
